### ISSUE TITLE
android  红米上报错

### ISSUE THREAD

**Issue by l114624915** [KinsomyJS/muses_weather_flutter#7]
I/authErrLog(  887): ================================================================================
I/authErrLog(  887):                                    鉴权错误信息                                  
I/authErrLog(  887): ================================================================================
I/authErrLog(  887): |SHA1Package:14:1F:67:38:EC:D5:32:6A:1A:DD:74:43:B4:91:18:B3:AB:65:D4:9F:com.gr|
I/authErrLog(  887): |een.kinsomy.musesweatherflutterexample                                        |
I/authErrLog(  887): |key:9d1c1cc3f1afeea63b288f0e91238298                                          |
I/authErrLog(  887): |csid:01eba538112f4d10b741e25fa8195596                                         |
I/authErrLog(  887): |gsid:cfc5a759d85ada8afcb1704240f44ed9                                         |
I/authErrLog(  887): |json:{"info":"INVALID_USER_SCODE","infocode":"10008","status":"0","sec_code_de|
I/authErrLog(  887): |bug":"e432a4731b1c1e00561891233454a6ce","key":"9d1c1cc3f1afeea63b288f0e9123829|
I/authErrLog(  887): |8","sec_code":"67bcc98dd494b7c86cd7d835e33cff03"}                             |
I/authErrLog(  887):                                                                                
I/authErrLog(  887): 请在高德开放平台官网中搜索"INVALID_USER_SCODE"相关内容进行解决
I/authErrLog(  887): ================================================================================

**Comment by KinsomyJS** [comment]
里面用了一个高德定位的插件，需要申请一个自己的高德定位key @l114624915 
具体看文章介绍 https://juejin.im/post/5be819a46fb9a049ea3878d7

**Comment by l114624915** [comment]
好的，谢谢
